### ISSUE TITLE
Opening a workspace opens two tabs after update

### ISSUE THREAD

**Issue by louy2** [msramalho/my-slack-workspaces#1]
I am using Firefox and for some reason two tabs are opened when I click on a workspace after update, one is the updated one while the other is the old one which would fail to log in.

**Comment by msramalho** [comment]
Thanks for the bug report @louy2, I'll try to investigate this over the next week.

**Comment by msramalho** [comment]
Quick update: this issue is not forgotten, but I have come against a lot of breaking changes with the new gulp version so this will probably take me some more time to fix, hopefully before the end of the month. (although the issue itself is essentially fixed x)
